FROM golang:1.25.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o backend-app .

FROM scratch

COPY --from=builder /app/backend-app /backend-app

EXPOSE 8080

CMD ["/backend-app"]
