services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  backend:
    image: hst-backend
    container_name: hst-backend
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017
    restart: on-failure

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: hst-portal
    ports:
      - "3000:4321"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0      

volumes:
  mongo-data: